set (QT_5 OFF)
set (QT_6 OFF)
unset (QT_MAJOR)
if (Qt6_DIR OR Qt6_ROOT)
	find_package (Qt6 REQUIRED COMPONENTS Core)
	if (Qt6_FOUND)
		set (QT_6 ON)
		set (QT_MAJOR 6)
	endif (Qt6_FOUND)
elseif (Qt5_DIR OR Qt5_ROOT)
	find_package (Qt5 REQUIRED COMPONENTS Core)
	if (Qt5_FOUND)
		set (QT_5 ON)
		set (QT_MAJOR 5)
	endif (Qt5_FOUND)
else ( )	# Spack ?
	find_package (Qt6 REQUIRED COMPONENTS Core)
	if (Qt6_FOUND)
		set (QT_6 ON)
		set (QT_MAJOR 6)
	else (Qt6_FOUND)
		find_package (Qt5 REQUIRED COMPONENTS Core)
		if (Qt5_FOUND)
			set (QT_5 ON)
			set (QT_MAJOR 5)
		else (Qt5_FOUND)
			message (FATAL_ERROR "Version majeure de Qt non gérée.")
		endif (Qt5_FOUND)
	endif (Qt6_FOUND)
endif ( )

