set (VTK_7 OFF)
set (VTK_8 OFF)
set (VTK_9 OFF)
set (USE_OPENGL_BACKEND OFF)
set (QVTK_WIDGET OFF)
find_package (VTK REQUIRED)
message (STATUS "VTK DETECTE : ${VTK_VERSION}")
if (VTK_VERSION_MAJOR STREQUAL "7")
	set (VTK_7 ON)
	set (USE_OPENGL_BACKEND ON)
	set (QVTK_WIDGET ON)
elseif (VTK_VERSION_MAJOR STREQUAL "8")
	set (VTK_8 ON)
elseif (VTK_VERSION_MAJOR STREQUAL "9")
	set (VTK_9 ON)
else ( )
	message (FATAL_ERROR "Version majeure de VTK non gérée : ${VTK_VERSION}")
endif ( )

