#
# version.cmake : version du projet
#

set (GUI_TOOLKITS_VARIABLES_MAJOR_VERSION "1")
set (GUI_TOOLKITS_VARIABLES_MINOR_VERSION "6")
set (GUI_TOOLKITS_VARIABLES_RELEASE_VERSION "0")
set (GUI_TOOLKITS_VARIABLES_VERSION ${GUI_TOOLKITS_VARIABLES_MAJOR_VERSION}.${GUI_TOOLKITS_VARIABLES_MINOR_VERSION}.${GUI_TOOLKITS_VARIABLES_RELEASE_VERSION})
